// <auto-generated />
using Labb3_2._5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_2._5.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230503074031_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_2._5.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FK_PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.HasIndex("FK_PersonId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Walk in the woods",
                            FK_PersonId = 1,
                            Title = "Walking"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "Code C#",
                            FK_PersonId = 2,
                            Title = "Code"
                        },
                        new
                        {
                            InterestId = 3,
                            Description = "Swim faster",
                            FK_PersonId = 3,
                            Title = "Swiming"
                        },
                        new
                        {
                            InterestId = 4,
                            Description = "Marathon",
                            FK_PersonId = 4,
                            Title = "Running"
                        },
                        new
                        {
                            InterestId = 5,
                            Description = "Flowers in all colour",
                            FK_PersonId = 1,
                            Title = "Garden Work"
                        });
                });

            modelBuilder.Entity("Labb3_2._5.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("FK_InterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkId");

                    b.HasIndex("FK_InterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            FK_InterestId = 1,
                            Url = "Walk.com"
                        },
                        new
                        {
                            LinkId = 2,
                            FK_InterestId = 2,
                            Url = "CoDelike_a_pro.com"
                        },
                        new
                        {
                            LinkId = 3,
                            FK_InterestId = 3,
                            Url = "Swiming.com"
                        },
                        new
                        {
                            LinkId = 4,
                            FK_InterestId = 4,
                            Url = "Running.com"
                        },
                        new
                        {
                            LinkId = 5,
                            FK_InterestId = 5,
                            Url = "Flowers.uk.com"
                        });
                });

            modelBuilder.Entity("Labb3_2._5.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "Gösta Göstasson",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Eva Evasson",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Lennart Lennartsson",
                            PhoneNumber = "0918273645"
                        },
                        new
                        {
                            PersonId = 4,
                            Name = "Lena Lenasson",
                            PhoneNumber = "1122334455"
                        },
                        new
                        {
                            PersonId = 5,
                            Name = "Jesus Jesusson",
                            PhoneNumber = "99887766"
                        });
                });

            modelBuilder.Entity("Labb3_2._5.Models.Interest", b =>
                {
                    b.HasOne("Labb3_2._5.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("FK_PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb3_2._5.Models.Link", b =>
                {
                    b.HasOne("Labb3_2._5.Models.Interest", "Interest")
                        .WithMany()
                        .HasForeignKey("FK_InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");
                });
#pragma warning restore 612, 618
        }
    }
}
